In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\viper\Desktop\NOTES\AI_ML_DS\Projects\Beverages_price\synthetic_beverage_sales_data.csv")

In [3]:
df

Order_ID Customer_ID Customer_Type              Product  \
0              ORD1     CUS1496           B2B           Vio Wasser   
1              ORD1     CUS1496           B2B                Evian   
2              ORD1     CUS1496           B2B               Sprite   
3              ORD1     CUS1496           B2B   Rauch Multivitamin   
4              ORD1     CUS1496           B2B         Gerolsteiner   
...             ...         ...           ...                  ...   
8999905  ORD2999999     CUS7080           B2C        Schwip Schwap   
8999906  ORD2999999     CUS7080           B2C       San Pellegrino   
8999907  ORD3000000     CUS6551           B2B             Red Bull   
8999908  ORD3000000     CUS6551           B2B  Passion Fruit Juice   
8999909  ORD3000000     CUS6551           B2B               Vittel   

            Category  Unit_Price  Quantity  Discount  Total_Price  \
0              Water        1.66        53      0.10        79.18   
1              Water        1.56        90      0.10       126.36   
2        Soft Drinks        1.17        73      0.05        81.14   
3             Juices        3.22        59      0.10       170.98   
4              Water        0.87        35      0.10        27.40   
...              ...         ...       ...       ...          ...   
8999905  Soft Drinks        1.27         2      0.00         2.54   
8999906        Water        0.91        15      0.00        13.65   
8999907  Soft Drinks        2.94        64      0.10       169.34   
8999908       Juices        4.04        79      0.10       287.24   
8999909        Water        0.38         9      0.10         3.08   

                    Region  Order_Date  
0        Baden-Württemberg  2023-08-23  
1        Baden-Württemberg  2023-08-23  
2        Baden-Württemberg  2023-08-23  
3        Baden-Württemberg  2023-08-23  
4        Baden-Württemberg  2023-08-23  
...                    ...         ...  
8999905            Sachsen  2023-07-03  
8999906            Sachsen  2023-07-03  
8999907     Sachsen-Anhalt  2022-04-09  
8999908     Sachsen-Anhalt  2022-04-09  
8999909     Sachsen-Anhalt  2022-04-09  

[8999910 rows x 11 columns]

In [5]:
df.shape

(8999910, 11)

In [6]:
df.head()

Order_ID Customer_ID Customer_Type             Product     Category  \
0     ORD1     CUS1496           B2B          Vio Wasser        Water   
1     ORD1     CUS1496           B2B               Evian        Water   
2     ORD1     CUS1496           B2B              Sprite  Soft Drinks   
3     ORD1     CUS1496           B2B  Rauch Multivitamin       Juices   
4     ORD1     CUS1496           B2B        Gerolsteiner        Water   

   Unit_Price  Quantity  Discount  Total_Price             Region  Order_Date  
0        1.66        53      0.10        79.18  Baden-Württemberg  2023-08-23  
1        1.56        90      0.10       126.36  Baden-Württemberg  2023-08-23  
2        1.17        73      0.05        81.14  Baden-Württemberg  2023-08-23  
3        3.22        59      0.10       170.98  Baden-Württemberg  2023-08-23  
4        0.87        35      0.10        27.40  Baden-Württemberg  2023-08-23

In [7]:
df.isnull().sum()

Order_ID         0
Customer_ID      0
Customer_Type    0
Product          0
Category         0
Unit_Price       0
Quantity         0
Discount         0
Total_Price      0
Region           0
Order_Date       0
dtype: int64

In [43]:
from sklearn.preprocessing import LabelEncoder

In [48]:
le=LabelEncoder()

In [34]:
le=(df["beverage_category"])=le.fit_transform(df["Category"])

In [38]:
le=(df["product_cat"])=le.fit_transform(df["Product"])

In [45]:
le=(df["customer_cat"])=le.fit_transform(df["Customer_Type"])

In [50]:
le=(df["region_cat"])=le.fit_transform(df["Region"])

In [51]:
le

array([ 0,  0,  0, ..., 13, 13, 13], shape=(8999910,))

In [52]:
df

Order_ID Customer_ID Customer_Type              Product  \
0              ORD1     CUS1496           B2B           Vio Wasser   
1              ORD1     CUS1496           B2B                Evian   
2              ORD1     CUS1496           B2B               Sprite   
3              ORD1     CUS1496           B2B   Rauch Multivitamin   
4              ORD1     CUS1496           B2B         Gerolsteiner   
...             ...         ...           ...                  ...   
8999905  ORD2999999     CUS7080           B2C        Schwip Schwap   
8999906  ORD2999999     CUS7080           B2C       San Pellegrino   
8999907  ORD3000000     CUS6551           B2B             Red Bull   
8999908  ORD3000000     CUS6551           B2B  Passion Fruit Juice   
8999909  ORD3000000     CUS6551           B2B               Vittel   

            Category  Unit_Price  Quantity  Discount  Total_Price  \
0              Water        1.66        53      0.10        79.18   
1              Water        1.56        90      0.10       126.36   
2        Soft Drinks        1.17        73      0.05        81.14   
3             Juices        3.22        59      0.10       170.98   
4              Water        0.87        35      0.10        27.40   
...              ...         ...       ...       ...          ...   
8999905  Soft Drinks        1.27         2      0.00         2.54   
8999906        Water        0.91        15      0.00        13.65   
8999907  Soft Drinks        2.94        64      0.10       169.34   
8999908       Juices        4.04        79      0.10       287.24   
8999909        Water        0.38         9      0.10         3.08   

                    Region  Order_Date  beverage_category  product_cat  \
0        Baden-Württemberg  2023-08-23                  3           42   
1        Baden-Württemberg  2023-08-23                  3            9   
2        Baden-Württemberg  2023-08-23                  2           38   
3        Baden-Württemberg  2023-08-23                  1           29   
4        Baden-Württemberg  2023-08-23                  3           12   
...                    ...         ...                ...          ...   
8999905            Sachsen  2023-07-03                  2           36   
8999906            Sachsen  2023-07-03                  3           34   
8999907     Sachsen-Anhalt  2022-04-09                  2           30   
8999908     Sachsen-Anhalt  2022-04-09                  1           27   
8999909     Sachsen-Anhalt  2022-04-09                  3           43   

         customer_cat  region_cat  
0                   0           0  
1                   0           0  
2                   0           0  
3                   0           0  
4                   0           0  
...               ...         ...  
8999905             1          12  
8999906             1          12  
8999907             0          13  
8999908             0          13  
8999909             0          13  

[8999910 rows x 15 columns]

In [ ]:
x=df[["beverage_category","product_cat","customer_cat","region_cat","Unit_Price","Quantity","Discount"]]
y=df["Total_Price"]

In [57]:
from sklearn.linear_model import LinearRegression

In [58]:
mdl=LinearRegression()

In [61]:
mdl.fit(x,y)

LinearRegression()

In [68]:
df[["Total_Price","beverage_category","product_cat","customer_cat","region_cat","Unit_Price","Quantity","Discount","Customer_Type","Product","Category","Region"]]

Total_Price  beverage_category  product_cat  customer_cat  \
0              79.18                  3           42             0   
1             126.36                  3            9             0   
2              81.14                  2           38             0   
3             170.98                  1           29             0   
4              27.40                  3           12             0   
...              ...                ...          ...           ...   
8999905         2.54                  2           36             1   
8999906        13.65                  3           34             1   
8999907       169.34                  2           30             0   
8999908       287.24                  1           27             0   
8999909         3.08                  3           43             0   

         region_cat  Unit_Price  Quantity  Discount Customer_Type  \
0                 0        1.66        53      0.10           B2B   
1                 0        1.56        90      0.10           B2B   
2                 0        1.17        73      0.05           B2B   
3                 0        3.22        59      0.10           B2B   
4                 0        0.87        35      0.10           B2B   
...             ...         ...       ...       ...           ...   
8999905          12        1.27         2      0.00           B2C   
8999906          12        0.91        15      0.00           B2C   
8999907          13        2.94        64      0.10           B2B   
8999908          13        4.04        79      0.10           B2B   
8999909          13        0.38         9      0.10           B2B   

                     Product     Category             Region  
0                 Vio Wasser        Water  Baden-Württemberg  
1                      Evian        Water  Baden-Württemberg  
2                     Sprite  Soft Drinks  Baden-Württemberg  
3         Rauch Multivitamin       Juices  Baden-Württemberg  
4               Gerolsteiner        Water  Baden-Württemberg  
...                      ...          ...                ...  
8999905        Schwip Schwap  Soft Drinks            Sachsen  
8999906       San Pellegrino        Water            Sachsen  
8999907             Red Bull  Soft Drinks     Sachsen-Anhalt  
8999908  Passion Fruit Juice       Juices     Sachsen-Anhalt  
8999909               Vittel        Water     Sachsen-Anhalt  

[8999910 rows x 12 columns]

x=df[["beverage_category","product_cat","customer_cat","region_cat","Unit_Price","Quantity","Discount"]]
y=df["Total_Price"]

In [67]:
mdl.predict([[3,42,0,0,1.66,53,0.10]])

C:\Users\viper\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([195.19894076])

In [ ]:
actual_price=df["Total_Price"]==126.36


In [72]:
mdl.predict([[3,9,0,0,1.56,90,0.10]])

C:\Users\viper\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([426.13653433])

In [77]:
ls=abs(actual_price-(mdl.predict([[3,9,0,0,1.56,90,0.10]])))

C:\Users\viper\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [83]:
ls[0]

np.float64(426.1365343281351)

In [84]:
import joblib


In [85]:
dump=joblib.dump(mdl,r"C:\Users\viper\Desktop\NOTES\AI_ML_DS\Projects\Beverages_price\beverages_price.pkl")

In [88]:
df.Category.unique()

array(['Water', 'Soft Drinks', 'Juices', 'Alcoholic Beverages'],
      dtype=object)

In [89]:
df.Customer_Type.unique()


array(['B2B', 'B2C'], dtype=object)

In [90]:
df.Product.unique()


array(['Vio Wasser', 'Evian', 'Sprite', 'Rauch Multivitamin',
       'Gerolsteiner', 'Sauvignon Blanc', 'Tomato Juice', 'Vittel',
       'San Pellegrino', 'Mountain Dew', 'Hohes C Orange', 'Red Bull',
       'Chardonnay', 'Tanqueray', 'Rotkäppchen Sekt', 'Mango Juice',
       'Apollinaris', 'Riesling', 'Granini Apple', 'Fanta', 'Rockstar',
       'Club Mate', 'Krombacher', 'Erdinger Weißbier', 'Volvic Touch',
       'Volvic', 'Schwip Schwap', 'Fritz-Kola', 'Coca-Cola', 'Selters',
       'Cranberry Juice', 'Mezzo Mix', "Beck's", 'Passion Fruit Juice',
       'Monster', 'Augustiner', 'Pepsi', 'Merlot', 'Kölsch', 'Bacardi',
       'Warsteiner', 'Moët & Chandon', 'Jever', 'Veuve Clicquot',
       'Johnnie Walker', 'Havana Club', 'Jack Daniels'], dtype=object)

In [91]:
df.Region.unique()

array(['Baden-Württemberg', 'Schleswig-Holstein', 'Hamburg', 'Bayern',
       'Saarland', 'Thüringen', 'Brandenburg', 'Nordrhein-Westfalen',
       'Mecklenburg-Vorpommern', 'Sachsen-Anhalt', 'Niedersachsen',
       'Rheinland-Pfalz', 'Bremen', 'Sachsen', 'Hessen', 'Berlin'],
      dtype=object)